name: Copy marcket repository

on:
  workflow_dispatch:

jobs:
  copy-target:
      name: copy target.yml
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: clone marcket_g8_n1
          uses: actions/checkout@v2
          with:
            repository: t-ube/marcket_g8_n1
            path: marcket_g8_n1
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: clone marcket_g8_m1
          uses: actions/checkout@v2
          with:
            repository: t-ube/marcket_g8_m1
            path: marcket_g8_m1
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: clone marcket_g8_l1
          uses: actions/checkout@v2
          with:
            repository: t-ube/marcket_g8_l1
            path: marcket_g8_l1
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: copy data
          run: |
            mkdir -p marcket
            find marcket_g8_n1/dist/* -type f -maxdepth 0 -exec cp {} marcket/ \;
            find marcket_g8_m1/dist/* -type f -maxdepth 0 -exec cp {} marcket/ \;
            find marcket_g8_l1/dist/* -type f -maxdepth 0 -exec cp {} marcket/ \;
        - name: clean marckets
          run: | 
            rm -rf marcket_g8_n1
            rm -rf marcket_g8_m1
            rm -rf marcket_g8_l1
        - name: Commit files
          run: |
            git config --local user.email "ube@coder.okinawa.jp"
            git config --local user.name "Tomoyuki UBE"
            git add marcket
            git diff-index --quiet HEAD || git commit -m "[BOT] Copy from repo"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ steps.extract_branch.outputs.branch }}
