name: Daily auto

on:
  workflow_dispatch:

jobs:
  copy-target:
      name: copy target.yml
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: clone marcket_g8_n1
          uses: actions/checkout@v2
          with:
            repository: t-ube/marcket_g8_n1
            path: marcket_g8_n1
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: clone marcket_g8_m1
          uses: actions/checkout@v2
          with:
            repository: t-ube/marcket_g8_m1
            path: marcket_g8_m1
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: clone marcket_g8_l1
          uses: actions/checkout@v2
          with:
            repository: t-ube/marcket_g8_l1
            path: marcket_g8_l1
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: clone ptc_event
          uses: actions/checkout@v2
          with:
            repository: t-ube/ptc_event
            path: ptc_event
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: copy data
          run: |
            mkdir -p marcket
            mkdir -p log
            find marcket_g8_n1/dist/* -type f -maxdepth 0 -exec cp {} marcket/ \;
            find marcket_g8_m1/dist/* -type f -maxdepth 0 -exec cp {} marcket/ \;
            find marcket_g8_l1/dist/* -type f -maxdepth 0 -exec cp {} marcket/ \;
            find marcket_g8_n1/log/* -type f -maxdepth 0 -exec cp {} log/ \;
            find marcket_g8_m1/log/* -type f -maxdepth 0 -exec cp {} log/ \;
            find marcket_g8_l1/log/* -type f -maxdepth 0 -exec cp {} log/ \;
            mkdir -p event
            find ptc_event/dist/* -type f -maxdepth 0 -exec cp {} event/ \;
        - name: clean marckets
          run: | 
            rm -rf marcket_g8_n1
            rm -rf marcket_g8_m1
            rm -rf marcket_g8_l1
            rm -rf ptc_event
        - name: Commit files
          run: |
            git config --local user.email "ube@coder.okinawa.jp"
            git config --local user.name "Tomoyuki UBE"
            git add marcket
            git add log
            git add event
            git diff-index --quiet HEAD || git commit -m "[BOT] Copy from repo"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ steps.extract_branch.outputs.branch }}
  build:
    name: Process calc
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.13'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pandas==1.2.0 numpy==1.19.5 BeautifulSoup4==4.9.3 requests==2.28.1 urllib3==1.26.12 typer==0.6.1 python-decouple==3.6 pytest==7.1.3
    - name: Build data
      run: |
        python3 new_calc.py
    - name: Commit files
      run: |
        git config --local user.email "ube@coder.okinawa.jp"
        git config --local user.name "Tomoyuki UBE"
        git add dist
        git diff-index --quiet HEAD || git commit -m "[BOT] crawler"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
