name: Write supabase

on:
  workflow_dispatch:

jobs:
  update:
      name: write
      runs-on: ubuntu-latest
      env:
        SUPABASE_URL: ${{secrets.SUPABASE_URL}}
        SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9.13'
        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install pandas==1.2.0 numpy==1.19.5 BeautifulSoup4==4.9.3 requests==2.28.1 urllib3==1.26.12 typer==0.6.1 python-decouple==3.6 pytest==7.1.3 supabase==0.7.1
        - name: Write data
          run: |
            python3 save_supabase.py
